[package]
name = "mcrs_engine"
description = "mcrs_engine"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true, features = ["track_location"] }
rustc-hash.workspace = true
tracing = "0.1.43"

[features]

[profile.dev.package."bevy"]
opt-level = 3







